/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as timeLockControllerSol from "./TimeLockController.sol";
export type { timeLockControllerSol };
export type { GovernanceToken } from "./GovernanceToken";
export type { IPriceOracle } from "./IPriceOracle";
export type { ITimelockController } from "./ITimelockController";
export type { LendingPoolNovel } from "./LendingPoolNovel";
export type { Lock } from "./Lock";
export type { MockPriceOracle } from "./MockPriceOracle";
export type { NUSD } from "./NUSD";
export type { PlatformContract } from "./PlatformContract";
export type { PropertyToken } from "./PropertyToken";
export type { ReceiptToken } from "./ReceiptToken";
