/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPriceOracle } from "./IPriceOracle";
export type { ITimelockController } from "./ITimelockController";
export type { LendingPoolNovel } from "./LendingPoolNovel";
export type { ReceiptToken } from "./ReceiptToken";
