/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPriceOracle__factory } from "./IPriceOracle__factory";
export { ITimelockController__factory } from "./ITimelockController__factory";
export { LendingPoolNovel__factory } from "./LendingPoolNovel__factory";
export { ReceiptToken__factory } from "./ReceiptToken__factory";
